hysds/hysds

hysds/utils.py
test/test_utils.py

Made triage more robust by detecting directories and files and copying them to triage dataset accordingly.

HC-121: detect directories and backup correctly

---

hysds/utils.py
test/test_utils.py

Use timestamp to differentiate filename clashes.
Added unit test.

HC-40: ensure overlap dir/files being triaged are copied

---

setup.py

@DustinKLo: Please review. In order for development of HySDS core v3 to continue concurrent to HySDS core v4 development, we need to pin msgpack in `develop` since `develop` is technically still HySDS core v3 (logstash 1.5.5). This fix isn't needed in `develop-es7` branch but should be merged in from `develop` once this PR is merged so as to maintain the branch history (i.e. when we finally merge `develop-es7` into `develop` we won't have to worry about resolving this conflict).

ping msgpack; version 1.0.0 introduces breaking changes

---

.gitignore
configs/celery/celeryconfig.py.tmpl
configs/logstash/event_status.template
configs/logstash/indexer.conf.mozart
configs/logstash/job_status.template
configs/logstash/task_status.template
configs/logstash/worker_status.template
configs/supervisor/supervisord.conf.mozart
hysds/__init__.py
hysds/es_util.py
hysds/orchestrator.py
hysds/user_rules_dataset.py
hysds/user_rules_job.py
hysds/utils.py
requirements.txt

* Hc 142 user rules (#43)
* created deprecated folder to add older user rules py files
* removed .idea/
* edited gitignore
* refactored user_rules_dataset.py to use elasticsearch library
.raw -> .keyword
TODO: need to fix update_query function to be compatible with ES7
* fixed comment
* fixed update query in user_rule_dataset.py to be compatible with ES7
* added hysdsio argument in user_rules_job.queue_job_trigger
* removed 'hysdsio': '_doc' from user_rules_job.py
* extra space is bothering me
* Hc 153 logstash (#46)
* bump version
* edited indexer.conf.template
edited job_status.template
TODO: edit other index mapping templates
* removed unused parameters from indexer.conf.template
* edited template for event_status
* fixed mapping template for eventn and worker
* fixed indexer.conf and …

Develop es7 (#52)

---

hysds/job_worker.py
hysds/log_utils.py

In conjunction with the updates to `lightweight-jobs` (https://github.com/hysds/lightweight-jobs/pull/17), this PR update the `run_job()` function to check redis if its task id was marked as revoked. If it is marked as revoked, it fires the `revoke()` function so that the appropriate signal handler is executed.

HC-205: add revoked task check

---

hysds/es_util.py

```
>>> from hysds.es_util import get_grq_es
>>> grq_es = get_grq_es()
/export/home/hysdsops/mozart/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py:116: UserWarning: Connecting to https://vpce-#######-######.vpce-svc-#######.us-west-#.vpce.amazonaws.com:443 using SSL with verify_certs=False is insecure.
% self.host
>>> grq_es.es.info()
{'name': '6a085e466b8afaf71ef350492e7e03cd', 'cluster_name': '271039147104:nisar-dev', 'cluster_uuid': 't_nlyhQDRNqvEu5GHBC8ng', 'version': {'number': '7.1.1', 'build_flavor': 'oss', 'build_type': 'tar', 'build_hash': '7a013de', 'build_date': '2019-09-05T07:25:23.525600Z', 'build_snapshot': False, 'lucene_version': '8.0.0', 'minimum_wire_compatibility_version': '6.8.0', 'minimum_index_compatibility_version': '6.0.0-beta1'}, 'tagline': …
```

fixed aws es_url

---

hysds/__init__.py
hysds/es_util.py

https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch
```
es = Elasticsearch(
['localhost:443', 'other_host:443'],
use_ssl=True,
verify_certs=False,
ssl_show_warn=False
)
```

cleaner way to Ignore SSL warnings

---

hysds/__init__.py
hysds/utils.py
requirements.txt

- handle no microseconds
- mitigate CVE-2020-10108 and CVE-2020-10109
- bump version

HC-215: handle datestring conversions without microseconds (backport to develop-es1)

---

hysds/__init__.py
scripts/sync_ec2_target_tracking_metric.py

Currently, the ec2 syncer script that updates CloudWatch metrics has to manually bootstrap the ASG because previously the target tracking capability needed at least one instance up in the ASG to scale up.
This PR removes that bootstrap mechanism so that the ASG can scale up immediately.
This PR was tested and verified on a NISAR dev cluster.

HC-266: remove syncer script bootstrap mechanism

---

scripts/sync_ec2_target_tracking_metric.py

Previous update remove bootstrapping the ASG to 1 and relied on target tracking for initial scale up. However target tracking takes a few minutes to kick in on that initial scale up and adds latency to job execution. This hotfix restores the bootstrap functionality but bootstraps the ASG's `desired capacity == jobs waiting`.

restore ASG bootstrap but modify for immediate scale-up

---

hysds/utils.py
test/test_utils.py

This PR fixes an issue where essentially if you keep re-running a job on a triage dataset, you'll eventually get a `[Errno 36] File name too long` as the triage dataset name will keep getting longer for each run. This PR addresses the issue by adding a `task` identifier to the default triage dataset name: 
`triaged_job-{job_id}_task-{job[task_id]}`
Then, in the triage function, logic was added to check for a triage dataset name using the following regex:
`triaged_job-(?P<job_id>.+)_task-(?P<task_id>[-\\w])`
If we get a match, then the `job_id` is used as the job identifier instead of using the default `job["job_info"]["id"]`
The following screenshot shows the result of running a job on a triaged dataset. This demonstrates that all we're doing is updating the task id in the triaged dataset …

HC-242: Resolved file name too long issue

---

configs/logstash/indexer.conf.metrics

Previous PR which added sdswatch indexer disabled auto rotating of indexes by date. Now we need to explicitly specify this.

HC-277: hotfix to explicitly set rotating indexes by date

---

setup.py

related ticket: https://hysds-core.atlassian.net/browse/HC-278
after locking the version, celery workers run as normal
```
$ supervisorctl status all
flower                                                                   RUNNING   pid 12810, uptime 0:00:23
instance_stats                                                           RUNNING   pid 12811, uptime 0:00:23
logstash_indexer                                                         RUNNING   pid 12812, uptime 0:00:23
mozart_job_management                                                    RUNNING   pid 12813, uptime 0:00:23
orchestrator_datasets:orchestrator_datasets-00                           RUNNING   pid 12814, uptime 0:00:23
orchestrator_datasets:orchestrator_datasets-01                           RUNNING   pid 12816, uptime …
```

locked celery version to >=4.4.0,<5.0.0

---

setup.py

the `dev-e2e` nightly for hysds v3 is failing, i suspect its because of changes to celery
https://nisar-pcm-ci.jpl.nasa.gov/job/nightlies/job/v3/job/develop-es1/job/E2E-nisar-pcm-develop-baseline-pge/358/display/redirect

locked celery version for hysds v3

---

hysds/job_worker.py

Update the RFC_6598_RE regular expression to support a bigger IP range, specifically 100.64.x.x - 100.127.x.x
Tested it out on my local cluster on swot and it checked out fine.

HC-280: Update RFC_6598_RE to support a bigger range

---

.circleci/config.yml

Created contexts `docker-hub-creds` and `git-oauth-token` and updated CircleCI config for authenticated docker pulls.

HC-281: authenticate docker hub pulls

---

hysds/job_worker.py

This PR enables the propagation of data publishing metrics from a manual call to `publish_datasets()` within the job docker container through to the job status JSON payload. Test and development is being performed internally on NISAR dev.

HC-313: extend product publishing metrics from manual ingests within the job

---

scripts/harikiri.py
scripts/harikiri_sqs.py
scripts/spot_termination_detector.py
setup.py

Updated the existing harikiri and spot_termination_detector scripts to support the passing in of a configuration file to read tool arguments from. The user will still have the ability to pass in arguments through the command line. Anything specified on the command line will take precedence over whatever gets specified in the configuration file. See the comments in the associated Jira ticket of how it was tested.

HC-300: improvements to core systemd services: harikiri and spot_termination_detector

---

hysds/__init__.py
scripts/harikiri.py
scripts/harikiri_sqs.py
scripts/spot_termination_detector.py

This PR will add logging messages wherever exceptions are being caught,
but proceeding onward. This will help us in the future in case issues
arise.
Also updated the function name from `daemon` to `spot_termination_detector` for better readability in the logs. Right
now it shows it like this:
```
Feb  5 00:03:30 ip-172-31-27-171 bash: [2021-02-05 00:03:30,216:
INFO/daemon] configuration:
Feb  5 00:03:30 ip-172-31-27-171 bash: [2021-02-05 00:03:30,216:
INFO/daemon] mozart_rest_url=https://100.64.122.239/mozart/api/v0.1
Feb  5 00:03:30 ip-172-31-27-171 bash: [2021-02-05 00:03:30,216:
INFO/daemon] check=30
```

HC-300 Patch: Add logging messages wherever exceptions are caught

---

configs/logstash/sdswatch_client-pcm.conf
hysds/__init__.py

This PR adds an SDSWatch client configuration file for use on the mozart, metrics, and grq PCM components. See https://hysds-core.atlassian.net/browse/HC-273 for end-to-end test results.

HC-273: provision SDSWatch client on PCM components: mozart, metrics, and grq

---

hysds/__init__.py
hysds/job_worker.py
hysds/log_utils.py
hysds/orchestrator.py
hysds/utils.py

This PR provides better support for detecting dedup jobs in the system. When the `query_dedup_job` function is called, it will first try to store the payload hash in REDIS. If it detects that it already exists, we will perform exponential backoff when trying to find the dedup job. This allows us to try and catch jobs with the same payload that may have been submitted at the same time. On the caller side, specifically at the orchestrator and job_worker levels, the calling of the `query_dedup_job` function is now surrounded by a try/except block to catch `NoDedupJobFoundException` exceptions so we can set the result to None if the hash key exists in REDIS and we cannot find the dedup job at the end of the exponential backoff.
This feature was tested on a local cluster, where this change was …

HC-334: Improve dedup detection

---

configs/supervisor/supervisord.conf.mozart

will return an error when trying to connect to jenkins
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)
```
https://opendev.org/jjb/python-jenkins/src/branch/master/jenkins/__init__.py#L345-L350 says to set environment variable `PYTHONHTTPSVERIFY=0`

add PYTHONHTTPSVERIFY environment variable in supervisor.conf.mozart

---

hysds/__init__.py
hysds/dataset_ingest.py
hysds/utils.py
test/test_utils.py

This PR adds more robust exception handling in the `triage` post-processor function and prevents jobs from failing when there are issues accessing additional file/directory globs. A new unit test was also added to test this feature.

HC-363: catch errors copying additional paths for triage

---

hysds/job_worker.py

This PR fixes the issue where the `.running` signal file is not transitioned to `.done` because the remote services running on remote servers (e.g. ES, redis, or rabbitmq-server running on mozart) is not reachable. By transitioning the signal file upfront before these remote calls, the harikiri process on each verdi worker will be able to detect all jobs as being done and terminate the instance accordingly.

HC-374: failed job not detected as done causing harikiri to leave worker instances up

---

hysds/es_util.py

sometimes making requests to AWS ES raises this error, [Stackoverflow](https://stackoverflow.com/a/27253193) recommends adding a `timeout` and `retry` when initializing the connection to ES
```python
es = Elasticsearch(timeout=30, max_retries=10, retry_on_timeout=True)
```
```
File "/home/######/######/ops/#######/util/exec_util.py", line 22, in wrapper
status = func(*args, **kwargs)
File "/home/######/######/ops/#######/Track_Frame_Accountability/eval_track_frame.py", line 150, in evaluate
) = get_stuf_info_from_xml(input_begin_date_time, input_end_date_time)
File "/home/######/######/ops/#######/util/stuf_util.py", line 28, in get_stuf_info_from_xml
results = ancillary_es.perform_es_range_intersection_query(
File …
```

added timeout to aws es connection

---

configs/logstash/job_status.template
hysds/job_worker.py

This PR adds the capability such that informational messages can get propagated up to the UI. This is useful for successful jobs that do not produce any output. 2 new fields are added to the job_status json:
- msg: Intended for short messages much like the error field. Can be a string or an array of strings.
- msg_details: Contains a detailed informational message.
If the worker finds an `_alt_msg.txt` file, it will add it to the `msg` field in the job_status. Additionally, if the `_alt_msg_details.txt` file is found, then it will add the string value to the `msg_details` in the job_status.

HC-302: Add capability to propagate info messages up to the UI for successful jobs

---

configs/celery/celeryconfig.py.tmpl
hysds/__init__.py
scripts/harikiri_sqs.py
scripts/sync_ec2_target_tracking_metric.py
setup.py

This PR updates HySDS core to use celery v5.1.2 and additionally updates the `celeryconfig.py.tmpl` template to include `json` as acceptable content, which is the format of broadcasted revoke payloads.
This was tested in NISAR using the NASA demo pipeline (dev-e2e + ALOS L0B processed to RSLC, GSLC and GCOV).

HC-380, HC-383, HC-384: update to celery v5.1.2, accept json content to receive revokes, mitigate autoscaling API throttling

---

requirements.txt

related ticket(s): 
* https://jira.jpl.nasa.gov/browse/NSDS-1571
* https://hysds-core.atlassian.net/browse/HC-386
Starting in ES v7.14 it will make a check if the client is compatible and will raise an error 
https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/release-notes.html#rn-7-14-0
this is because of the conflict between Elastico and AWS
* https://github.com/elastic/elasticsearch-py/blob/61e7a130979edd46af5ead00b03c25f71e0a2886/elasticsearch/transport.py#L412-L413
* https://github.com/elastic/elasticsearch-py/commit/44d9e0de761e17851f29c4d07b6c87ed381fb29e
```python
raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch
```
will need to pin the …

pin elasticsearch>=7.0.0,7.14.0

---

configs/supervisor/supervisord.conf.mozart
hysds/__init__.py
requirements.txt
scripts/harikiri.py
scripts/harikiri_sqs.py
scripts/sync_ec2_target_tracking_metric.py

This PR addresses both https://hysds-core.atlassian.net/browse/HC-393 and https://hysds-core.atlassian.net/browse/HC-398.
This PR updates the `sync_ec2_target_tracking_metric.py` script by adding a new option (`-t, --total_jobs`) that modifies the custom metric that is sent for an autoscaling group target tracking policy. The default when not specifying that option (to maintain backwards compatibility) is the current behavior to send the ratio of waiting/queued jobs to desired_count to the `JobsWaitingPerInstance-*` custom metric. When that option is specified, the ratio of total jobs to desired_count is sent to the `JobsPerInstance-*` custom metric instead.
To test backwards compatibility, this new script was run in NISAR against the `dev-e2e (fwd)`, `dev-e2e (reprocessing)`, …

HC-393, HC-398: Fix UTC time handling in harikiri & add target tracking metric for autoscaling that allows for 1:1 scaling of jobs to workers

---

hysds/__init__.py
scripts/harikiri.py
scripts/harikiri_sqs.py

This hotfix addresses a race condition that can result in the harikiri*.py script running on a worker to terminate the instance it's running on. The specific scenario where this happens is this:
1. Upon instance startup, the harikiri*.py script starts up via systemd.
2. Since no jobs have been run yet, the `NO_JOBS_TIMER` will have been set to a recorded timestamp: https://github.com/hysds/hysds/blob/2fb20d85e4af9ce653185e5e811503ed61369069/scripts/harikiri_sqs.py#L128
3. The celery worker running `run_job` picks up jobs to run and has not yet exercised any cleanup of old work directories via https://github.com/hysds/hysds/blob/2fb20d85e4af9ce653185e5e811503ed61369069/hysds/job_worker.py#L276-L317.
4. A subsequent job is picked up that triggers the cleanup of **ALL** old work directories …

hotfix: handle race condition between job_worker cleanup and harikiri scripts

---

hysds/__init__.py
hysds/dataset_ingest.py
hysds/dataset_ingest_bulk.py

change(s):
- `r.raise_for_status()` doesn't propagate the error to grq2's error to the Figaro UI, raising the error manually instead
- bumped version
related PR: https://github.com/hysds/grq2/pull/55
related ticket: https://hysds-core.atlassian.net/browse/HC-425
```
[2022-08-24 18:46:23,148: INFO/ForkPoolWorker-1] Backing off bulk_index_dataset(...) for 0.5s (hysds.dataset_ingest_bulk.NotAllProductsIngested: {"success": false, "message": "Error: <class 'NameError'>:name 'fsjdkfshdkjfsdhkfjs' is not defined\nTraceback (most recent call last):\n  File \"/export/home/hysdsops/sciflo/ops/grq2/grq2/services/api_v02/datasets.py\", line 127, in post\n    print(fsjdkfshdkjfsdhkfjs)\nNameError: name 'fsjdkfshdkjfsdhkfjs' is not defined\n", "objectid": null, "index": null})
```

HC-425 - propagate Elasticsearch errors encountered during dataset indexing in grq2

---

scripts/clean_job_status_indexes.py
scripts/clean_job_status_indexes.sh
scripts/clean_mozart_indexes.sh

This PR updates the clean up scripts to properly clean out the job status indices. 
During testing, it was discovered that when running the `sds -d reset mozart` command, the following error message was appearing:
```
[100.104.10.166] run: ~/mozart/ops/hysds/scripts/clean_job_status_indexes.sh http://100.104.10.166:9200
[100.104.10.166] out: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [job_status-current] matches an alias, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [job_status-current] matches an alias, specify the corresponding concrete indices instead."},"status":400}
```
Therefore, the `cleanup_job_status_indexes.sh` script was updated such that we will …

HC-447 (update): Update Mozart clean up scripts to properly remove job_status indices

---

scripts/clean_job_status_indexes.py

- This PR updates the handling of non-existent aliases within the `delete_job_status()` function.
- This PR is related to https://github.jpl.nasa.gov/IEMS-SDS/swot-pcm/pull/502 (Add mechanism for rolling off old ES indices in Metrics ES).
- This branch was used in a  SWOT PCM end-to-end smoke test, linked below.
- forward-using-MOE: [![Build Status](https://swot-pcm-ci.jpl.nasa.gov/buildStatus/icon?job=force-branches%2Falgermis-force_branch-E2E-test&build=572)](https://swot-pcm-ci.jpl.nasa.gov/job/force-branches/job/algermis-force_branch-E2E-test/572/)

HC-447-update-2: Update handling of non-existent aliases

---

configs/logstash/indexer.conf.mozart
scripts/clean_indices_from_alias.py
scripts/process_events.py

https://jira.jpl.nasa.gov/browse/NSDS-2584
related PR: https://github.com/sdskit/sdscli/pull/99
change(s):
- created `clean_indices_from_alias.py` to delete index by alias passed by `argv`
- `worker` and `event` index name will have date time appended through logstash
- `task` index name now has date time through the `event` body; (for clobbering) similar to how its done for `job_status-*`

NSDS-2584 - Implement rollover of old task, worker, event ES docs on Mozart ES

---

setup.py

related issue: https://github.com/redis/redis-py/issues/2629
```
[2023-03-20 22:28:46,583: WARNING/process_events] Received method (60, 60) during closing channel 1. This method will be ignored
File "/export/home/hysdsops/mozart/ops/hysds/scripts/process_events.py", line 256, in <module>
event_monitor(app)
File "/export/home/hysdsops/mozart/ops/hysds/scripts/process_events.py", line 252, in event_monitor
recv.capture(limit=None, timeout=None, wakeup=True)
File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/celery/events/receiver.py", line 91, in capture
for _ in self.consume(limit=limit, timeout=timeout, wakeup=wakeup):
File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/kombu/mixins.py", line 193, in consume …
```

pin redis-py

---

hysds/__init__.py
setup.py

With https://github.com/hysds/hysds/pull/155, the redis module was setup to not include 4.5.2. However, 4.5.3 was just released yesterday and unfortunately, it broke the cluster provisioners with the same Socket Timeout error:
Therefore, it's probably best to make the pin `<4.5.2` as opposed to `!=4.5.2` for the time being.

hot-fix: Make redis pin less than 4.5.2

---

hysds/__init__.py
hysds/dataset_ingest_bulk.py

Related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-458
- https://hysds-core.atlassian.net/browse/HC-460
- https://jira.jpl.nasa.gov/browse/NSDS-2703
- using celery's `multiprocessing` library (`billiard`) to parallelize the publishing of datasets
- parallelizing the rollback of datasets as well
- bump version
when testing on a job that produces 300 `hello_world` datasets with a 150MB file each
- when using parallelization on a 16cpu verdi worker: ~3 minutes
- publishing datasets synchronously (one-by-one): ~50 minutes
dev-e2e (reproc): [![Build Status](https://nisar-pcm-ci.jpl.nasa.gov/job/force-branches/job/dustinlo-force_branch-E2E-test/27/badge/icon)](https://nisar-pcm-ci.jpl.nasa.gov/job/force-branches/job/dustinlo-force_branch-E2E-test/27/)

HC-460: address performance of publishing products

---

hysds/__init__.py
hysds/dataset_ingest_bulk.py

b/c we're not properly raising the error, it only logs it and technically the job will complete

HOTFIX: forgot to raise error when async_publish_files fails

---

hysds/__init__.py
hysds/orchestrator.py

Related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-465
- During testing, a bug was found in which de-duped jobs were not being stored in the jobs database and were not visible on the Figaro UI. The only way to identify that the job was deduped was through Mozart's orchestrator logs.
- The fix was to include the `job_status` ES index in the `job_info` at the beginning of the `submit_job()` function within `orchestrator.py`. The `job_status` ES index was previously only being included for those jobs which get queued, however, for jobs that are not queued (de-duped, invalid, etc.), the `job_status` ES index was never set in the `job_info`. This led to those jobs never appearing in the jobs database's `job_status` index.
- Using the HC-465 HySDS branch on Mozart:
- Copy the same …

HC-465: Fixed to properly log dedup jobs

---

hysds/__init__.py
hysds/job_worker.py

Related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-468
Change(s):
- commented out docker_stats exception, instead logging it
- bump version
sometimes when a job fails it will not write to the `_docker_stats.json` file, leaving it a blank file
```
File "/home/ops/verdi/ops/hysds-1.2.3/hysds/job_worker.py", line 1464, in run_job
usage_stats = json.load(f)
File "/opt/conda/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/opt/conda/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/opt/conda/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/opt/conda/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise …
```

HC-468: handle zero-length docker stats files

---

hysds/user_rules_dataset.py
setup.py

https://github.com/hysds/hysds/issues/170
[2023-06-15 12:35:08,714: INFO/ForkPoolWorker-1] Backing off search_es(...) for 9.5s (elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'failed to parse setting [timeout] with value [30] as a time value: unit is missing or unrecognized'))
[2023-06-15 12:35:18,246: WARNING/ForkPoolWorker-1] POST http://100.104.10.49:9200/grq/_search?timeout=30 [status:400 request:0.002s]
[2023-06-15 12:35:18,246: INFO/ForkPoolWorker-1] Backing off search_es(...) for 48.7s (elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'failed to parse setting [timeout] with value [30] as a time value: unit is missing or unrecognized'))

HC-170: time value: unit is missing or unrecognized error with grq search timeout call

---

hysds/__init__.py
hysds/dataset_ingest.py
hysds/dataset_ingest_bulk.py
hysds/job_worker.py
hysds/localize.py
hysds/utils.py
setup.py

related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-472
related PR(s):
- https://github.com/hysds/osaka/pull/38
related articles:
- https://pythonspeed.com/articles/python-multiprocessing/
- https://superfastpython.com/multiprocessing-deadlock/
- https://britishgeologicalsurvey.github.io/science/python-forking-vs-spawn/#other-multiprocessing-tricks
**change(s):**
- moved `localize_urls` from `utils.py` to its own dedicated file, `localize.py`
- added addtl' logic in `download_file` that removes the `.osaka.locked.json` if it errors
- new function `find_non_localized_datasets` to filter out datasets with a `.localized` file
- this is to prevent over-using cores on datasets that would not be published
- separated functions into parallelized and non-parallelized
- separated …

HC-472: fix issues with concurrent osaka downloads and uploads using multiprocessing: deadlocks and IMDS query throttling

---

hysds/utils.py

There appears to be an issue with the recent changes made in https://github.com/hysds/hysds/pull/174
Didn't notice this before, but it looks like in the querying of the dedup jobs, that PR updated the function to use mozart_es instead of the requests call:
However, it forgot to take into account gracefully ignoring 404 errors.

hot-fix: Ignore 404 errors as we had before when making requests calls

---

hysds/job_worker.py
hysds/user_rules_job.py

Change(s):
- passing the job doc's index to userrules task
- removed alias 'job_status' in favor of `job_status-current` in user rules job evaluation
Related ticket:
- https://hysds-core.atlassian.net/browse/HC-482
Related PR(s):
- https://github.com/hysds/lightweight-jobs/pull/29
Jenkins:
- dev-e2e (reproc): https://nisar-pcm-ci.jpl.nasa.gov/job/force-branches/job/ci-force_branch-E2E-test/272/
- dev-e2e (fwd): https://nisar-pcm-ci.jpl.nasa.gov/job/force-branches/job/ci-force_branch-E2E-test/273/
`job_worker.py` will now pass the index to the user rules job evaluation, the logs:
```
[2023-07-12 23:15:39,472: INFO/ForkPoolWorker-1] hysds.task_worker.run_task[f31be517-7e03-49ac-8aef-7c02229db2f8]: Final query: {"query": {"bool": {"must": [{"bool": {"must": [{"bool": {"must": [{"term": …
```

HC-482: Make User Rule Job evaluation more targeted

---

scripts/watchdog_job_timeouts.py

This PR updates the job watchdog such that when it queries for worker events for a particular worker, it will sort the records by latest. We need to do this as the worker history can span across multiple indices now.
Once I made the fix, I deployed onto the Load Test cluster and it seems to be working fine now:
```
[2023-08-09 00:56:34,162: INFO/watchdog_job_timeouts] search **kwargs: {'index': 'worker_status-current', 'body': '{"query": {"term": {"_id": "celery@nisar-job_worker-datatake-acct.172.31.27.200"}}, "_source": ["status", "tags"], "sort": [{"@timestamp": "desc"}]}'}
[2023-08-09 00:56:34,163: INFO/watchdog_job_timeouts] POST http://127.0.0.1:9200/worker_status-current/_search [status:200 request:0.001s]
[2023-08-09 00:56:34,163: INFO/watchdog_job_timeouts] worker_res: {"took": 0, …
```

HC-489: Update Job Watchdog to sort worker queries by latest

---

configs/celery/celeryconfig.py.tmpl
hysds/event_processors.py
hysds/job_worker.py
hysds/orchestrator.py
hysds/utils.py
scripts/process_events.py

This PR updates the system to better handle jobs where connection timeouts occur, but never get caught by the system. Therefore, at the operator level, the jobs appear "stuck" at job-started or job-queued.
Here are the changes:
**Orchestrator**
Add backoff to the run_job call when submitting a job to be queued. We also reversed the order such that we make the call first, then set the job status to `job-queued` rather than the other way around as it was in the previous implementation. Lastly, if the exponential backoff still fails after it hits its max retries, then we added the capability to set the job status to `job-failed`, followed by sending it off to user rule job evaluation.
**Process Events**
Additionally look for ConnectionError task failures. When these kinds of failures occur, …

HC-493: Updates to better handle jobs that fail due to connection timeouts but are never persisted back up to the job status

---

configs/celery/celeryconfig.py.tmpl
configs/logstash/indexer.conf.metrics
configs/logstash/indexer.conf.mozart
configs/supervisor/supervisord.conf.metrics
hysds/__init__.py
hysds/es_util.py
hysds/job_worker.py
hysds/user_rules_dataset.py
hysds/user_rules_job.py
hysds/utils.py
requirements.txt
scripts/clean_es_cluster.py
scripts/clean_indices_from_alias.py
scripts/install_ilm_policy.py
scripts/install_job_status_template.py
setup.py
test/test_job_worker.py
test/test_preprocessing_checksum.py
test/test_triage.py
test/test_utils.py

related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-483
- https://hysds-core.atlassian.net/browse/HC-490
- https://hysds-core.atlassian.net/browse/HC-484
change(s):
- bump minor version
- Jinja template files now supporting multiple nodes, depending on the value(s) in `~/.sds/config`:
- `[MOZART|METRICS|GRQ]_ES_PVT_IP` not supporting YAML arrays or strings
- files affected: `celeryconfig.py` and logstash indexers
- `celeryconfig.py` now has `JOBS_ES_ENGINE`, `GRQ_ES_ENGINE` & `METRICS_ES_ENGINE`; `elasticsearch` or `opensearch`
- `hysds/es_util.py` will use either `Elasticsearch` or `OpenSearch` python class depending on `*_ES_ENGINE` in `celeryconfig.py`
- added python scripts to install ILM or ISM, depending on opensearch or elasticsearch
- …

HC-484: OpenSearch support

---

hysds/__init__.py
hysds/triage.py

This PR turns on clobbering when publishing triage datasets. This fixes an issue that was seen where jobs would be occasionally re-queued due to spot termination, but would result in a no-clobber when trying to re-publish the triage dataset.
To test, I put in a kludge so that I could essentially force the re-queued scenario. I then submitted a job to factotum and forced the re-queued scenario by restarting the factotum job worker in the middle of the job. As a result, it is verified that a redelivery of a job no longer results in a triage no-clobber:

HC-502: Enable clobbering when publishing triage datasets

---

setup.py

This hot fix pins lxml to less than 5.1.0 as 5.1.0 introduced the following error:
```
File "/home/ops/verdi/bin/sflExec.py", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/ops/verdi/ops/sciflo/scripts/sflExec.py", line 261, in <module>
results, resStrList = main()
File "/home/ops/verdi/ops/sciflo/scripts/sflExec.py", line 206, in main
results = sciflo.grid.executor.runSciflo(xml, argsDict, timeout=timeout,
File "/home/ops/verdi/ops/sciflo/sciflo/grid/executor.py", line 1079, in runSciflo
raise res
File "/home/ops/verdi/ops/sciflo/sciflo/grid/executor.py", line 1049, in _runSciflo
s = ScifloExecutor(sflStr, args=args, workers=workers,
File "/home/ops/verdi/ops/sciflo/sciflo/grid/executor.py", line 217, in __init__ …
```

hot-fix: Pin lxml to less than 5.1.0

---

setup.py

Through testing, it turns out lxml should be pinned to less than 5.0.0 in order to resolve the issue described in https://github.com/hysds/hysds/pull/184

hot-fix: Should pin lxml to less than 5.0.0

---

scripts/watchdog_job_timeouts.py

This PR resolves several issues seen with job worker watchdogs:
- Fix the calculation of the duration. Needs to be `total_seconds()`
- Sort the task status results by latest. This is because we only look at the top most result when determining what to do.
- Upon a task_failed status, propagate the error and traceback so that this eventually gets back up to Figaro
After making the changes, this was tested on the NISAR cluster and was verified that the job was properly moved to job failed with the timedout tag:

HC-520: Fix job worker watchdog to properly handle cases where hard time limit was reached

---

hysds/__init__.py
scripts/log_instance_stats.py

Due to psutil 6.0.0 release, it is found that it broke the instance_stats service with the following error:
```
File "/export/home/hysdsops/mozart/ops/hysds/scripts/log_instance_stats.py", line 119, in <module>
daemon(args.redis_url, args.redis_key, args.interval)
File "/export/home/hysdsops/mozart/ops/hysds/scripts/log_instance_stats.py", line 79, in daemon
for device, mnt_point, fs_type, fs_opts, max_file, max_path, *other in psutil.disk_partitions():
ValueError: not enough values to unpack (expected at least 6, got 4)
```
According to the psutil pull request, https://github.com/giampaolo/psutil/pull/2405, max_file and max_path were removed because if there's a NFS (network filesystem) this function can potentially take a long time to complete.
After …

hot-fix: Update return from psutil.disk_partitions function call

---

hysds/__init__.py
hysds/orchestrator.py

instead of having to exec import every time. This seems to improve CPU performance 3x.
Testing performed:
- I ran a single orchestrator celery worker on a Mozart machine in foreground and disabled all that are normally started by supervisord. I ran it using the same command that was in supervisord.conf.
- I queued 2000 jobs using the existing code without the caching change. It took about 42 seconds. Average CPU utilization was ~70% eyeballing using top over those 42 seconds.
- I stopped the process; change the code to add caching; restarted. Stopped and then reset Mozart to clear out mozart_es. Queued up the same 2000 jobs again. It took about 22 seconds with average CPU utilization of ~40%
- Restored supervisord.conf to start the orchestrator celery workers nominally and ran the OPERA …

HC-540: Cache the function objects being returned by orchestrator.py get_function method

---

configs/logstash/indexer.conf.mozart

This PR is in conjunction with the following other PRs:
- sdscli: https://github.com/sdskit/sdscli/pull/109
- lightweight jobs: https://github.com/hysds/lightweight-jobs/pull/34
This PR updates the logstash configuration such that when it sees a failed job, it will make sure to move it from `job_status` to `job_failed`. Note that we don't want to introduce any rollover since the intent is to preserve this failed jobs for further analysis and put the onus on the end user to purge this failed jobs eventually.
**Testing**
See comments in https://hysds-core.atlassian.net/browse/HC-546

HC-546: Update logstash to move a failed job over to a new job_failed index

---

hysds/__init__.py

This hot fix decreases the version to 1.3.3 since the version was already bumped in a previous PR since the last HySDS Core Release

hot-fix: should be 1.3.3 not 1.3.4

---

configs/celery/celeryconfig.py.tmpl
hysds/__init__.py
hysds/containers/base.py
hysds/containers/docker.py
hysds/containers/podman.py
hysds/job_worker.py

This PR makes the following updates to support the latest container changes in moving away from having the Verdi container default to the OPS user. In addition, these updates/bug fixes are due to the latest testing efforts that were done within the HECC environment:
- The default `PODMAN_CFG` in the celeryconfig.py no longer sets the `--userns=keep-id` flag or the setting of the `-u` flag option by default. Therefore, `root` is the default user when running podman now, which means the host user in the podman world due to our rootless podman mode set up.
- `VERDI_HOME` defaults to `/root` now since the Verdi container now moves away from defaulting to an OPS user. `/root` is also now where the HySDS Core code resides in now.
- celeryconfig.py passes in the `HOST_USER` environment variable …

HC-522-update: Updates to support moving away from OPS user

---

configs/logstash/indexer.conf.mozart
hysds/__init__.py
hysds/job_worker.py
hysds/user_rules_job.py
test/test_triage.py

This PR fixes an issue to allow the auto-retrying of jobs, via the Figaro trigger rules, to work properly once again. Prior to queueing up the job for user rule evaluation, we should check to see if the status is job-failed and if so, set the index to job_failed when queuing up the job for user_rule_evaluation. This allows the user_rule_evaluation to work properly as it will now query for the job in the correct index rather than the specific job_status partitioned index at which it originated.
This PR is in conjunction with https://github.com/hysds/lightweight-jobs/pull/35
For testing, I ran a one-day reprocessing test on a cluster in SWOT and verified that all the auto-retries due to worker termination were retried successfully. Also verified that we did not have any lingering leftover …

HC-556: Fix to make the auto-retrying of jobs work properly again

---

configs/celery/celeryconfig.py.tmpl
hysds/__init__.py

The RabbitMQ timeout thresholds were updated to 30 seconds from the default 4 second threshold. This update was shown to improve the performance, especially during heavy processing loads. See the screenshot of the before and after in https://hysds-core.atlassian.net/browse/HC-565
Kudos to @stirlingalgermissen for the great find.

HC-565: Increase timeout thresholds in the RabbitMQ configuration file

---

configs/celery/celeryconfig.py.tmpl
hysds/__init__.py
hysds/containers/base.py
hysds/job_worker.py
hysds/utils.py
test/test_docker_container_utils.py

… cache eviction; use HYSDS_ROOT_WORK_DIR for cache base (#201)
* HC-571: Add capability to set a custom cache base directory when downloading files
* Update name to be more clear
* update doc
* Add capability to make the cache dir read-write access
* Update
* Add capability to disable eviction of cache
* Add logging messages
* Make the default the HYSDS_ROOT_WORK_DIR directory, but fallback to the ROOT_WORK_DIR setting in celeryconfig
* persist HYSDS_ROOT_WORK_DIR
* update unit test
---------

Merge develop into develop-dit

---

hysds/job_worker.py

This PR addresses a known race condition in the `job_worker.py` where a job could be revoked or fail after the .done file is created by the `task_revoked_handler`, but before the `os.rename` call in `run_job()` attempts to move the .running file.
The `os.rename(job_running_file, job_done_file)` call can throw an Errno 2 (No such file or directory) error because the .running file may no longer exist, having been handled by the revocation signal.
This change introduces a check to ensure that the os.rename operation is only attempted if the job_running_file exists. If it doesn't, it checks for the existence of the .done file to avoid any redundant operations. This makes the job completion logic more resilient to race conditions and ensures that the .done file is always properly created …

HC-581: Resolve issue where job fails due to .running file not found
