- scripts/check_job_periodicity.py
Tested on dev cluster. Closes #6.
> initial implementation of job periodicity watchdog

- scripts/check_job_periodicity.py
> watchdog script for job periodicity check

- .circleci/config.yml
- test/test_version.py
> test import

- hysds/__init__.py
- hysds/container_utils.py
- hysds/job_worker.py
- test/test_container_utils.py
Implemented, added unit tests, and updated documentation at https://hysds-core.atlassian.net/wiki/spaces/HYS/pages/199787836/Job+and+HySDS+IO+Specifications.
> HC-127: gpu support

- requirements.txt
Details at https://hysds-core.atlassian.net/browse/HC-167.
> HC-167: migrate to community-developed flask-restx

- requirements.txt
End-to-end test ran successfully on NISAR dev cluster.
> HC-175: install flask-restx v0.2.0 to address issues with werkzeug v1.0.0

- hysds/user_rules_dataset.py
- hysds/user_rules_job.py
refactored `update_query` to be more flexible and to return a value instead of updating the inputed dictionary
cleaner to follow code and debug
> refactored update_query in user_rules_dataset and user_rules_job

- hysds/utils.py
https://hysds-core.atlassian.net/browse/HC-212
> fixed check_dataset in hysds.utils

- scripts/check_job_periodicity.py
- scripts/check_queue_periodicity.py
git push --set-upstream origin ARIA-17-es7
> ARIA-17: watchdog for mozart job timedout

- hysds/__init__.py
- hysds/utils.py
- requirements.txt
https://hysds-core.atlassian.net/projects/HC/issues/HC-215.
> HC-215: handle datestring conversions without microseconds

- hysds/__init__.py
- scripts/clean_event_status_indexes.sh
- scripts/clean_job_status_indexes.sh
- scripts/clean_mozart_indexes.sh
- scripts/clean_task_status_indexes.sh
- scripts/clean_worker_status_indexes.sh
- fix errors encountered when calling `sds reset mozart`:
```
module.common.aws_instance.mozart (remote-exec): [xxx.xxx.xxx.xxx] run: ~/mozart/ops/hysds/scripts/clean_job_status_indexes.sh http://xxx.xxx.xxx.xxx:9200
module.common.aws_instance.mozart (remote-exec): [xxx.xxx.xxx.xxx] out: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Wildcard expressions or all indices are not allowed"}],"type":"illegal_argument_exception","reason":"Wildcard expressions or all indices are not allowed"},"status":400}
module.common.aws_instance.mozart (remote-exec): [xxx.xxx.xxx.xxx] run: ~/mozart/ops/hysds/scripts/clean_task_status_indexes.sh http://xxx.xxx.xxx.xxx:9200
module.common.aws_instance.mozart (remote-exec): [xxx.xxx.xxx.xxx] out: …
```
> fix issues with clean scripts; bump version

- hysds/user_rules_dataset.py
- hysds/user_rules_job.py
not really related to soft time limit and disk usage, but just wanted to reformat some code
https://hysds-core.atlassian.net/browse/HC-171
> formatting changes to user rules

- configs/supervisor/supervisord.conf.factotum
- configs/supervisor/supervisord.conf.mozart
- hysds/__init__.py
- hysds/dataset_ingest.py
Details on this PR is located at https://hysds-core.atlassian.net/browse/HC-284.
Additionally, this also lowers the default number of `user_rules_*` celery workers running on factotum.
Testing done in NISAR I&T NITT-02 test (1488 NEN files).
> HC-284: remove bloat from context

- scripts/check_queue_periodicity.py
https://hysds-core.atlassian.net/browse/HC-279
> clean up code in check_queue_periodicity.py

- hysds/__init__.py
- requirements.txt
- scripts/log_instance_stats.py
- setup.py
This PR updates the call to psutil's disk_partitions function due to API changes recently made. See the comment on the associated Jira ticket for evidence that this change resolves the issue.
> HC-310: Update call to psutil's disk_partitions function

- configs/logstash/job_status.template
This PR mitigates the issue described in https://hysds-core.atlassian.net/browse/HC-371.
Testing in NISAR...
> HC-371: handle malformed ES field job.comand.argument in job status payloads

- hysds/dataset_ingest.py
- hysds/recognize.py
Allow the ipath to be templatable.
> HC-375: make ipath templatable

- configs/logstash/sdswatch_client.conf
These updates will extend sdswatch fulldict logging capabilities to within PGE's.
> added file entry for pge fulldict

- .circleci/config.yml
- .gitignore
- hysds/__init__.py
ticket: https://hysds-core.atlassian.net/browse/HC-431
https://hysds-core.atlassian.net/wiki/spaces/HYS/pages/2045837313/Publishing+HySDS+core+packages+to+PyPI
changes:
- added more to `.gitignore`
- added a new CircleCI workflow
- build & unit test the package
- publish to PyPI servers
- edited `setup.py` to better display in PyPI page
- bump version
> HC-431 - Make hysds-framework conda installable

- hysds/__init__.py
- hysds/dataset_ingest_bulk.py
- hysds/utils.py
Related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-458
- https://hysds-core.atlassian.net/browse/HC-461
Change(s):
- parallelizing the localization of products
- adding a retry + backoff to error out only if the data localization fails 5 times & prevents other localization afterwards
> HC-461: async localize

- hysds/__init__.py
- hysds/user_rules_dataset.py
[![Build Status](https://swot-pcm-ci.jpl.nasa.gov/buildStatus/icon?job=force-branches%2Falgermis-force_branch-E2E-test&build=6)](https://swot-pcm-ci.jpl.nasa.gov/job/force-branches/job/algermis-force_branch-E2E-test/6/)
> HC-471: Resolve time out issue when doing user rule evaluation

- hysds/user_rules_dataset.py
- hysds/user_rules_job.py
- hysds/utils.py
related ticket: https://hysds-core.atlassian.net/browse/HC-476
Change(s):
- lowered sleep in user rules evaluation to 6 & 7 seconds b/c the index refresh rate is 5 seconds now
- added `index_pattern` to user_rules dataset evaluation
- added `validate_index_pattern` utility function
> HC-476: Make user dataset rule evaluation more efficient/targetted

- hysds/__init__.py
- hysds/job_worker.py
> HC-473: Implement publish_overwrite_ok as a toggle to existing context var
